DEFAULT_MODE = "mouse"  # "mouse" or "evf"
MODE_CHORD_SECONDS = 1.0

POLL_INTERVAL = 0.010
DEBOUNCE_SECONDS = 0.025

CALIBRATION_SAMPLES = 80
CALIBRATION_SAMPLE_DELAY = 0.010
JOYSTICK_DEADZONE = 0.12
JOYSTICK_CURVE = 2.0
INVERT_X = False
INVERT_Y = True

MOUSE_MAX_SPEED = 14
DOUBLE_CLICK_DELAY = 0.075

EVF_AXIS_EPSILON = 0.02
EVF_AXIS_INTERVAL = 0.025

DEBUG_CONSOLE = True
